[platformio]
src_dir = .
include_dir = .
test_dir = Core/Test
default_envs = release

[env:release]
platform = ststm32
upload_protocol = stlink
debug_tool = stlink
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200
extra_scripts = pre:scripts/build_script.py

board = nucleo_c092kc
board_build.ldscript = STM32C092XX_FLASH.ld

build_flags =
    -std=gnu23
    -DUSE_HAL_DRIVER
    -ICore/Inc
    -ICore/Inc/cooling/fsm
    -ICore/Inc/cooling/post
    -ICore/Inc/cooling/can-communication
    -ICore/Inc/cooling/temperatures
    -ICore/Inc/cooling/control
    -IDrivers/CMSIS/Include/
    -IDrivers/STM32C0xx_HAL_Driver/Inc/
    -IDrivers/STM32H7xx_HAL_Driver/Inc/Legacy/
    -IDrivers/CMSIS/Device/ST/STM32C0xx/Include/

build_src_filter =
    +<Core/Src/>
    +<Drivers/STM32C0xx_HAL_Driver/Src/>
    -<Drivers/STM32C0xx_HAL_Driver/Src/*_template.c>
    +<./startup_stm32c092xx.s>

lib_deps =
    https://github.com/eagletrt/libeagletrt-sw#v0.1.0
    https://github.com/eagletrt/libpal-sw.git#v0.1.0
    https://github.com/eagletrt/libpid-sw.git#task/update-conventions-and-examples

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*,-bugprone-easily-swappable-parameters
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false
check_src_filters =
    -<**>
    +<Core/Src/cooling>
    +<Core/Inc/cooling>

[env:tests]
platform = native
test_framework = unity
test_build_src = true
build_flags =
    -std=gnu23
    -DEAGLETRT_STATIC=
    -DEAGLETRT_STATIC_INLINE=
    -ICore/Inc/cooling/temperatures
    -ICore/Inc/cooling/can-communication
    -ICore/Inc/cooling/control
    -ICore/Test/include

build_src_filter =
    +<Core/Src/cooling/temperatures/>
    +<Core/Src/cooling/can-communication/>
    +<Core/Src/cooling/control/>

lib_deps =
    https://github.com/eagletrt/libeagletrt-sw#v0.1.0
    https://github.com/eagletrt/libpal-sw.git#v0.1.0
    https://github.com/eagletrt/libpid-sw.git#task/update-conventions-and-examples

[env:bootloader]
platform = ststm32
upload_protocol = stlink
debug_tool = stlink
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200
extra_scripts = pre:scripts/build_script.py

board = nucleo_c092kc
board_build.ldscript = cooling-board-bootloader/STM32C092XX_FLASH.ld

build_flags =
    -std=gnu23
    -DUSE_HAL_DRIVER
    -Icooling-board-bootloader/Core/Inc
    -Icooling-board-bootloader/Drivers/CMSIS/Include/
    -Icooling-board-bootloader/Drivers/STM32C0xx_HAL_Driver/Inc/
    -Icooling-board-bootloader/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy/
    -Icooling-board-bootloader/Drivers/CMSIS/Device/ST/STM32C0xx/Include/

build_src_filter =
    +<cooling-board-bootloader/Core/Src/>
    +<cooling-board-bootloader/Drivers/STM32C0xx_HAL_Driver/Src/>
    -<cooling-board-bootloader/Drivers/STM32C0xx_HAL_Driver/Src/*_template.c>
    +<cooling-board-bootloader/startup_stm32c092xx.s>
