/******************************************************************************
Finite State Machine
Project: cooling_fsm
Description: Cooling board FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-06-18 15:17:16 +0200
Generated from: assets/fsm/fsm.dot
The finite state machine has:
  4 states
  5 transition functions

Functions and types have been generated with prefix "fsm_"

******************************************************************************/

#ifndef FSM_H
#define FSM_H
#ifdef __cplusplus
extern "C" {
#endif
#include <stdlib.h>

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
typedef void fsm_state_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
    FSM_STATE_INIT = 0,
    FSM_STATE_IDLE,
    FSM_STATE_ERROR,
    FSM_STATE_FLASH,
    FSM_NUM_STATES,
    FSM_NO_CHANGE
} fsm_state_t;

// State human-readable names
extern const char *fsm_state_names[];

// State function and state transition prototypes
typedef fsm_state_t state_func_t(fsm_state_data_t *data);
typedef void transition_func_t(fsm_state_data_t *data);

// State functions
// Function to be executed in state init
// valid return states: FSM_STATE_IDLE, FSM_STATE_ERROR
fsm_state_t fsm_do_init(fsm_state_data_t *data);
// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR
fsm_state_t fsm_do_idle(fsm_state_data_t *data);
// Function to be executed in state error
// valid return states: FSM_NO_CHANGE, FSM_STATE_ERROR
fsm_state_t fsm_do_error(fsm_state_data_t *data);
// Function to be executed in state flash
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR
fsm_state_t fsm_do_flash(fsm_state_data_t *data);

// List of state functions
extern state_func_t *const fsm_state_table[FSM_NUM_STATES];

// Transition functions
void fsm_init_done(fsm_state_data_t *data);
void fsm_init_error(fsm_state_data_t *data);
void fsm_start_flash(fsm_state_data_t *data);
void fsm_error_detected(fsm_state_data_t *data);
void fsm_flash_done(fsm_state_data_t *data);

// Table of transition functions
extern transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES];

// state manager
fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data);

#ifdef __cplusplus
}
#endif
#endif // FSM_H
